
Skip to content
Pull requests
Issues
Marketplace
Explore
@shagun-d
rapidops /
salesmate-service-template
Private template

3
0

    0

Code
Issues
Pull requests 1
Actions
Projects
Wiki
Security
Insights

    Settings

salesmate-service-template/.github/workflows/main.yml
@shagun-d
shagun-d create main.yaml file for github action
Latest commit 3c15d5b 10 minutes ago
History
1 contributor
44 lines (36 sloc) 1.29 KB
# This is a basic workflow to help you get started with Actions

name: learn-github-actions-ci
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: shaggy219/aws-google-sdk:v1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: v1-npm-deps-      
      # Runs a single command using the runners shell
      - name: Static Analysis
        run:  |
          npm ci
          npm run lint
  unit-test:
    # The type of runner that job will run on
    runs-on: ubuntu-latest
    container: shaggy219/aws-google-sdk:v1
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
       - name: Unit test Analysis
         run:  |
           npm ci
           npm install --save-dev cucumber-junit
           npm run test

